services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/outscaleworldwide/n8n
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    autoDeploy: true
